// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\account\invite
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InviteRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite.InviteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InviteRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/invite", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite.InviteRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InviteRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/invite", rawUrl)
        {
        }
        /// <summary>
        /// Create or return the authenticated account&apos;s primary invite code. The callis idempotent for accounts that already have a primary invite code.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.CreateInviteResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.CreateInviteResponse?> PostAsync(global::Soenneker.Polymarket.OpenApiClient.Models.PerpsCreateAccountInviteRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.CreateInviteResponse> PostAsync(global::Soenneker.Polymarket.OpenApiClient.Models.PerpsCreateAccountInviteRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.Error400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Polymarket.OpenApiClient.Models.Error401.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Polymarket.OpenApiClient.Models.Error429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.Error500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.CreateInviteResponse>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.CreateInviteResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create or return the authenticated account&apos;s primary invite code. The callis idempotent for accounts that already have a primary invite code.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Polymarket.OpenApiClient.Models.PerpsCreateAccountInviteRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Polymarket.OpenApiClient.Models.PerpsCreateAccountInviteRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite.InviteRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite.InviteRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Invite.InviteRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
