// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ActivityType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TRADE")]
        #pragma warning disable CS1591
        Trade,
        #pragma warning restore CS1591
        [EnumMember(Value = "SPLIT")]
        #pragma warning disable CS1591
        Split,
        #pragma warning restore CS1591
        [EnumMember(Value = "MERGE")]
        #pragma warning disable CS1591
        Merge,
        #pragma warning restore CS1591
        [EnumMember(Value = "REDEEM")]
        #pragma warning disable CS1591
        Redeem,
        #pragma warning restore CS1591
        [EnumMember(Value = "REWARD")]
        #pragma warning disable CS1591
        Reward,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONVERSION")]
        #pragma warning disable CS1591
        Conversion,
        #pragma warning restore CS1591
        [EnumMember(Value = "DEPOSIT")]
        #pragma warning disable CS1591
        Deposit,
        #pragma warning restore CS1591
        [EnumMember(Value = "WITHDRAWAL")]
        #pragma warning disable CS1591
        Withdrawal,
        #pragma warning restore CS1591
        [EnumMember(Value = "YIELD")]
        #pragma warning disable CS1591
        Yield,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAKER_REBATE")]
        #pragma warning disable CS1591
        MakerRebate,
        #pragma warning restore CS1591
        [EnumMember(Value = "TAKER_REBATE")]
        #pragma warning disable CS1591
        TakerRebate,
        #pragma warning restore CS1591
        [EnumMember(Value = "REFERRAL_REWARD")]
        #pragma warning disable CS1591
        ReferralReward,
        #pragma warning restore CS1591
    }
}
