// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AutoCancelStatus : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Maximum number of auto-cancel triggers allowed per UTC day.</summary>
        public int? DailyLimit { get; set; }
        /// <summary>Deadline of the armed auto-cancel schedule, in Unix milliseconds. Zeromeans no schedule is armed. When the deadline passes, the exchange cancelsevery open order on the account and the schedule clears.</summary>
        public int? Deadline { get; set; }
        /// <summary>Unix-ms timestamp of the next UTC midnight when the daily triggercount resets to zero.</summary>
        public int? NextReset { get; set; }
        /// <summary>Number of times auto-cancel has fired for this account during thecurrent UTC day. Resets to zero at 00:00 UTC.</summary>
        public int? Triggered { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelStatus"/> and sets the default values.
        /// </summary>
        public AutoCancelStatus()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "daily_limit", n => { DailyLimit = n.GetIntValue(); } },
                { "deadline", n => { Deadline = n.GetIntValue(); } },
                { "next_reset", n => { NextReset = n.GetIntValue(); } },
                { "triggered", n => { Triggered = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("daily_limit", DailyLimit);
            writer.WriteIntValue("deadline", Deadline);
            writer.WriteIntValue("next_reset", NextReset);
            writer.WriteIntValue("triggered", Triggered);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
