// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Order side (optional, not used for midpoint calculation)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BookRequestSide
    {
        [EnumMember(Value = "BUY")]
        #pragma warning disable CS1591
        Buy,
        #pragma warning restore CS1591
        [EnumMember(Value = "SELL")]
        #pragma warning disable CS1591
        Sell,
        #pragma warning restore CS1591
    }
}
