// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BridgeGetStatusAddressPaginateParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "true")]
        #pragma warning disable CS1591
        TrueValue,
        #pragma warning restore CS1591
    }
}
