// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Instrument category</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Category
    {
        [EnumMember(Value = "equity")]
        #pragma warning disable CS1591
        Equity,
        #pragma warning restore CS1591
        [EnumMember(Value = "commodity")]
        #pragma warning disable CS1591
        Commodity,
        #pragma warning restore CS1591
        [EnumMember(Value = "index")]
        #pragma warning disable CS1591
        Index,
        #pragma warning restore CS1591
        [EnumMember(Value = "crypto")]
        #pragma warning disable CS1591
        Crypto,
        #pragma warning restore CS1591
    }
}
