// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Trader side (TAKER or MAKER)</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ClobTradeTraderSide
    {
        [EnumMember(Value = "TAKER")]
        #pragma warning disable CS1591
        Taker,
        #pragma warning restore CS1591
        [EnumMember(Value = "MAKER")]
        #pragma warning disable CS1591
        Maker,
        #pragma warning restore CS1591
    }
}
