// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ClobGetUserEarningsAndMarketsConfigOrderByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "max_spread")]
        #pragma warning disable CS1591
        MaxSpread,
        #pragma warning restore CS1591
        [EnumMember(Value = "min_size")]
        #pragma warning disable CS1591
        MinSize,
        #pragma warning restore CS1591
        [EnumMember(Value = "end_date")]
        #pragma warning disable CS1591
        EndDate,
        #pragma warning restore CS1591
        [EnumMember(Value = "earning_percentage")]
        #pragma warning disable CS1591
        EarningPercentage,
        #pragma warning restore CS1591
        [EnumMember(Value = "rate_per_day")]
        #pragma warning disable CS1591
        RatePerDay,
        #pragma warning restore CS1591
        [EnumMember(Value = "earnings")]
        #pragma warning disable CS1591
        Earnings,
        #pragma warning restore CS1591
        [EnumMember(Value = "spread")]
        #pragma warning disable CS1591
        Spread,
        #pragma warning restore CS1591
        [EnumMember(Value = "competitiveness")]
        #pragma warning disable CS1591
        Competitiveness,
        #pragma warning restore CS1591
        [EnumMember(Value = "question")]
        #pragma warning disable CS1591
        Question,
        #pragma warning restore CS1591
        [EnumMember(Value = "price")]
        #pragma warning disable CS1591
        Price,
        #pragma warning restore CS1591
        [EnumMember(Value = "market")]
        #pragma warning disable CS1591
        Market,
        #pragma warning restore CS1591
        [EnumMember(Value = "volume_24hr")]
        #pragma warning disable CS1591
        Volume24Hr,
        #pragma warning restore CS1591
    }
}
