// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ClobGetBalanceAllowanceAssetTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "COLLATERAL")]
        #pragma warning disable CS1591
        Collateral,
        #pragma warning restore CS1591
        [EnumMember(Value = "CONDITIONAL")]
        #pragma warning disable CS1591
        Conditional,
        #pragma warning restore CS1591
    }
}
