// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>RESOLVED_PARTIAL = the combo resolved at a fractional payout (e.g. a leg voided 50/50) — redemption pays the fractional value per share.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ComboPositionStatus
    {
        [EnumMember(Value = "OPEN")]
        #pragma warning disable CS1591
        Open,
        #pragma warning restore CS1591
        [EnumMember(Value = "PARTIAL")]
        #pragma warning disable CS1591
        Partial,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESOLVED_PARTIAL")]
        #pragma warning disable CS1591
        ResolvedPartial,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESOLVED_WIN")]
        #pragma warning disable CS1591
        ResolvedWin,
        #pragma warning restore CS1591
        [EnumMember(Value = "RESOLVED_LOSS")]
        #pragma warning disable CS1591
        ResolvedLoss,
        #pragma warning restore CS1591
    }
}
