// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ComboActivity : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Lifecycle amount; null on redeems.</summary>
        public double? AmountUsdc { get; set; }
        /// <summary>The block_number property</summary>
        public long? BlockNumber { get; set; }
        /// <summary>Combo condition ID (0x-prefixed, 62 hex chars / bytes31). Equals the market_id (unified) / conditionId (legacy) of isCombo rows on /activity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComboConditionId { get; set; }
#nullable restore
#else
        public string ComboConditionId { get; set; }
#endif
        /// <summary>The combo_position_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ComboPositionId { get; set; }
#nullable restore
#else
        public string ComboPositionId { get; set; }
#endif
        /// <summary>Deprecated. Use `type` instead.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventKind { get; set; }
#nullable restore
#else
        public string EventKind { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The legs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.ComboLeg>? Legs { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.ComboLeg> Legs { get; set; }
#endif
        /// <summary>The log_index property</summary>
        public int? LogIndex { get; set; }
        /// <summary>The module_id property</summary>
        public int? ModuleId { get; set; }
        /// <summary>Always Combinatorial.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ModuleKind { get; set; }
#nullable restore
#else
        public string ModuleKind { get; set; }
#endif
        /// <summary>Redeem payout; null on lifecycle events.</summary>
        public double? PayoutUsdc { get; set; }
        /// <summary>Deprecated. Use `type` instead.</summary>
        [Obsolete("")]
        public global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivitySide? Side { get; set; }
        /// <summary>The timestamp property</summary>
        public long? Timestamp { get; set; }
        /// <summary>RFC3339 UTC</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TxDttm { get; set; }
#nullable restore
#else
        public string TxDttm { get; set; }
#endif
        /// <summary>The tx_hash property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TxHash { get; set; }
#nullable restore
#else
        public string TxHash { get; set; }
#endif
        /// <summary>User Profile Address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserAddress { get; set; }
#nullable restore
#else
        public string UserAddress { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivity"/> and sets the default values.
        /// </summary>
        public ComboActivity()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivity"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivity CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivity();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount_usdc", n => { AmountUsdc = n.GetDoubleValue(); } },
                { "block_number", n => { BlockNumber = n.GetLongValue(); } },
                { "combo_condition_id", n => { ComboConditionId = n.GetStringValue(); } },
                { "combo_position_id", n => { ComboPositionId = n.GetStringValue(); } },
                { "event_kind", n => { EventKind = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "legs", n => { Legs = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.ComboLeg>(global::Soenneker.Polymarket.OpenApiClient.Models.ComboLeg.CreateFromDiscriminatorValue)?.AsList(); } },
                { "log_index", n => { LogIndex = n.GetIntValue(); } },
                { "module_id", n => { ModuleId = n.GetIntValue(); } },
                { "module_kind", n => { ModuleKind = n.GetStringValue(); } },
                { "payout_usdc", n => { PayoutUsdc = n.GetDoubleValue(); } },
                { "side", n => { Side = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivitySide>(); } },
                { "timestamp", n => { Timestamp = n.GetLongValue(); } },
                { "tx_dttm", n => { TxDttm = n.GetStringValue(); } },
                { "tx_hash", n => { TxHash = n.GetStringValue(); } },
                { "user_address", n => { UserAddress = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("amount_usdc", AmountUsdc);
            writer.WriteLongValue("block_number", BlockNumber);
            writer.WriteStringValue("combo_condition_id", ComboConditionId);
            writer.WriteStringValue("combo_position_id", ComboPositionId);
            writer.WriteStringValue("event_kind", EventKind);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.ComboLeg>("legs", Legs);
            writer.WriteIntValue("log_index", LogIndex);
            writer.WriteIntValue("module_id", ModuleId);
            writer.WriteStringValue("module_kind", ModuleKind);
            writer.WriteDoubleValue("payout_usdc", PayoutUsdc);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.ComboActivitySide>("side", Side);
            writer.WriteLongValue("timestamp", Timestamp);
            writer.WriteStringValue("tx_dttm", TxDttm);
            writer.WriteStringValue("tx_hash", TxHash);
            writer.WriteStringValue("user_address", UserAddress);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
