// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CommentProfile : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The baseAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseAddress { get; set; }
#nullable restore
#else
        public string BaseAddress { get; set; }
#endif
        /// <summary>The bio property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bio { get; set; }
#nullable restore
#else
        public string Bio { get; set; }
#endif
        /// <summary>The displayUsernamePublic property</summary>
        public bool? DisplayUsernamePublic { get; set; }
        /// <summary>The isCreator property</summary>
        public bool? IsCreator { get; set; }
        /// <summary>The isMod property</summary>
        public bool? IsMod { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The positions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.CommentPosition>? Positions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.CommentPosition> Positions { get; set; }
#endif
        /// <summary>The profileImage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileImage { get; set; }
#nullable restore
#else
        public string ProfileImage { get; set; }
#endif
        /// <summary>The profileImageOptimized property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.ImageOptimization? ProfileImageOptimized { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.ImageOptimization ProfileImageOptimized { get; set; }
#endif
        /// <summary>The proxyWallet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProxyWallet { get; set; }
#nullable restore
#else
        public string ProxyWallet { get; set; }
#endif
        /// <summary>The pseudonym property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Pseudonym { get; set; }
#nullable restore
#else
        public string Pseudonym { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.CommentProfile"/> and sets the default values.
        /// </summary>
        public CommentProfile()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.CommentProfile"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.CommentProfile CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.CommentProfile();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseAddress", n => { BaseAddress = n.GetStringValue(); } },
                { "bio", n => { Bio = n.GetStringValue(); } },
                { "displayUsernamePublic", n => { DisplayUsernamePublic = n.GetBoolValue(); } },
                { "isCreator", n => { IsCreator = n.GetBoolValue(); } },
                { "isMod", n => { IsMod = n.GetBoolValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "positions", n => { Positions = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.CommentPosition>(global::Soenneker.Polymarket.OpenApiClient.Models.CommentPosition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "profileImage", n => { ProfileImage = n.GetStringValue(); } },
                { "profileImageOptimized", n => { ProfileImageOptimized = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.ImageOptimization>(global::Soenneker.Polymarket.OpenApiClient.Models.ImageOptimization.CreateFromDiscriminatorValue); } },
                { "proxyWallet", n => { ProxyWallet = n.GetStringValue(); } },
                { "pseudonym", n => { Pseudonym = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("baseAddress", BaseAddress);
            writer.WriteStringValue("bio", Bio);
            writer.WriteBoolValue("displayUsernamePublic", DisplayUsernamePublic);
            writer.WriteBoolValue("isCreator", IsCreator);
            writer.WriteBoolValue("isMod", IsMod);
            writer.WriteStringValue("name", Name);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.CommentPosition>("positions", Positions);
            writer.WriteStringValue("profileImage", ProfileImage);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.ImageOptimization>("profileImageOptimized", ProfileImageOptimized);
            writer.WriteStringValue("proxyWallet", ProxyWallet);
            writer.WriteStringValue("pseudonym", Pseudonym);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
