// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>
    /// Reward configuration entry for a current rewards market
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrentRewardConfig : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Address of the reward asset</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AssetAddress { get; set; }
#nullable restore
#else
        public string AssetAddress { get; set; }
#endif
        /// <summary>End date of the rewards period</summary>
        public Date? EndDate { get; set; }
        /// <summary>Rewards config ID (always 0 on /rewards/markets/current)</summary>
        public int? Id { get; set; }
        /// <summary>Daily reward rate</summary>
        public double? RatePerDay { get; set; }
        /// <summary>Start date of the rewards period</summary>
        public Date? StartDate { get; set; }
        /// <summary>Total rewards amount</summary>
        public double? TotalRewards { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.CurrentRewardConfig"/> and sets the default values.
        /// </summary>
        public CurrentRewardConfig()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.CurrentRewardConfig"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.CurrentRewardConfig CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.CurrentRewardConfig();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asset_address", n => { AssetAddress = n.GetStringValue(); } },
                { "end_date", n => { EndDate = n.GetDateValue(); } },
                { "id", n => { Id = n.GetIntValue(); } },
                { "rate_per_day", n => { RatePerDay = n.GetDoubleValue(); } },
                { "start_date", n => { StartDate = n.GetDateValue(); } },
                { "total_rewards", n => { TotalRewards = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("asset_address", AssetAddress);
            writer.WriteDateValue("end_date", EndDate);
            writer.WriteIntValue("id", Id);
            writer.WriteDoubleValue("rate_per_day", RatePerDay);
            writer.WriteDateValue("start_date", StartDate);
            writer.WriteDoubleValue("total_rewards", TotalRewards);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
