// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DataGetV1BuildersVolumeTimePeriodParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "DAY")]
        #pragma warning disable CS1591
        Day,
        #pragma warning restore CS1591
        [EnumMember(Value = "WEEK")]
        #pragma warning disable CS1591
        Week,
        #pragma warning restore CS1591
        [EnumMember(Value = "MONTH")]
        #pragma warning disable CS1591
        Month,
        #pragma warning restore CS1591
        [EnumMember(Value = "ALL")]
        #pragma warning disable CS1591
        All,
        #pragma warning restore CS1591
    }
}
