// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DataGetV1MarketPositionsSortByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "TOKENS")]
        #pragma warning disable CS1591
        Tokens,
        #pragma warning restore CS1591
        [EnumMember(Value = "CASH_PNL")]
        #pragma warning disable CS1591
        CashPnl,
        #pragma warning restore CS1591
        [EnumMember(Value = "REALIZED_PNL")]
        #pragma warning disable CS1591
        RealizedPnl,
        #pragma warning restore CS1591
        [EnumMember(Value = "TOTAL_PNL")]
        #pragma warning disable CS1591
        TotalPnl,
        #pragma warning restore CS1591
    }
}
