// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Deposit status</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DepositStatus
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "confirmed")]
        #pragma warning disable CS1591
        Confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "removed")]
        #pragma warning disable CS1591
        Removed,
        #pragma warning restore CS1591
    }
}
