// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ExchangeStatistics : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>End timestamp in milliseconds</summary>
        public long? EndTimestamp { get; set; }
        /// <summary>Gross positive maker and taker trading fees in USD for the requested window, as an unformatted numeric string. Rebates, incentives, and referral payments are excluded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fees { get; set; }
#nullable restore
#else
        public string Fees { get; set; }
#endif
        /// <summary>One-sided open interest in USD notional at the latest complete sample before the requested window end, as an unformatted numeric string. Null when no complete sample is available.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpenInterest { get; set; }
#nullable restore
#else
        public string OpenInterest { get; set; }
#endif
        /// <summary>Timestamp of the open-interest sample in Unix milliseconds. Null when no complete sample is available.</summary>
        public long? OpenInterestTimestamp { get; set; }
        /// <summary>Start timestamp in milliseconds</summary>
        public long? StartTimestamp { get; set; }
        /// <summary>Matched trading volume in USD notional for the requested window, as an unformatted numeric string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Volume { get; set; }
#nullable restore
#else
        public string Volume { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.ExchangeStatistics"/> and sets the default values.
        /// </summary>
        public ExchangeStatistics()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.ExchangeStatistics"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.ExchangeStatistics CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.ExchangeStatistics();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "end_timestamp", n => { EndTimestamp = n.GetLongValue(); } },
                { "fees", n => { Fees = n.GetStringValue(); } },
                { "open_interest", n => { OpenInterest = n.GetStringValue(); } },
                { "open_interest_timestamp", n => { OpenInterestTimestamp = n.GetLongValue(); } },
                { "start_timestamp", n => { StartTimestamp = n.GetLongValue(); } },
                { "volume", n => { Volume = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("end_timestamp", EndTimestamp);
            writer.WriteStringValue("fees", Fees);
            writer.WriteStringValue("open_interest", OpenInterest);
            writer.WriteLongValue("open_interest_timestamp", OpenInterestTimestamp);
            writer.WriteLongValue("start_timestamp", StartTimestamp);
            writer.WriteStringValue("volume", Volume);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
