// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>TPSL grouping</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Grp
    {
        [EnumMember(Value = "order")]
        #pragma warning disable CS1591
        Order,
        #pragma warning restore CS1591
        [EnumMember(Value = "position")]
        #pragma warning disable CS1591
        Position,
        #pragma warning restore CS1591
    }
}
