// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Leaderboard : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Leaderboard row for the requested address. `rank` is absent when the account has no activity in the window, or when sorting by account value and that account has no computed equity in the published census. A collateral-only display fallback does not establish an equity rank.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.LeaderboardAccount? Account { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.LeaderboardAccount Account { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The entries property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.PerpsLeaderboardEntry>? Entries { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.PerpsLeaderboardEntry> Entries { get; set; }
#endif
        /// <summary>Leaderboard ranking metric</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.SortBy? SortBy { get; set; }
        /// <summary>Update timestamp in milliseconds</summary>
        public long? Timestamp { get; set; }
        /// <summary>Total number of ranked accounts</summary>
        public int? Total { get; set; }
        /// <summary>Leaderboard window, anchored to calendar UTC boundaries. `day` starts at 00:00 UTC today, `week` at Monday 00:00 UTC, `month` at the first of the month 00:00 UTC, `all` at exchange launch.</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.Window? Window { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Leaderboard"/> and sets the default values.
        /// </summary>
        public Leaderboard()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Leaderboard"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Leaderboard CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Leaderboard();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "account", n => { Account = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.LeaderboardAccount>(global::Soenneker.Polymarket.OpenApiClient.Models.LeaderboardAccount.CreateFromDiscriminatorValue); } },
                { "entries", n => { Entries = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.PerpsLeaderboardEntry>(global::Soenneker.Polymarket.OpenApiClient.Models.PerpsLeaderboardEntry.CreateFromDiscriminatorValue)?.AsList(); } },
                { "sort_by", n => { SortBy = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.SortBy>(); } },
                { "timestamp", n => { Timestamp = n.GetLongValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "window", n => { Window = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Window>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.LeaderboardAccount>("account", Account);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.PerpsLeaderboardEntry>("entries", Entries);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.SortBy>("sort_by", SortBy);
            writer.WriteLongValue("timestamp", Timestamp);
            writer.WriteIntValue("total", Total);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Window>("window", Window);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
