// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Confirmation decision.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MakerConfirmationRequestDecision
    {
        [EnumMember(Value = "CONFIRM")]
        #pragma warning disable CS1591
        Confirm,
        #pragma warning restore CS1591
        [EnumMember(Value = "DECLINE")]
        #pragma warning disable CS1591
        Decline,
        #pragma warning restore CS1591
    }
}
