// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>
    /// Result of a maker confirmation. Includes a snapshot, an execution handoff,or both, depending on whether the confirmation completed the bundle.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MakerConfirmationResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Handoff produced when a confirmed RFQ is ready for onchain execution.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.ExecutionHandoff? Execution { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.ExecutionHandoff Execution { get; set; }
#endif
        /// <summary>Point-in-time view of an RFQ and its competition/confirmation windows.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot? Snapshot { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot Snapshot { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationResult"/> and sets the default values.
        /// </summary>
        public MakerConfirmationResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "execution", n => { Execution = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.ExecutionHandoff>(global::Soenneker.Polymarket.OpenApiClient.Models.ExecutionHandoff.CreateFromDiscriminatorValue); } },
                { "snapshot", n => { Snapshot = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot>(global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.ExecutionHandoff>("execution", Execution);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot>("snapshot", Snapshot);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
