// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MarketPositionV1 : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The asset property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Asset { get; set; }
#nullable restore
#else
        public string Asset { get; set; }
#endif
        /// <summary>The avgPrice property</summary>
        public double? AvgPrice { get; set; }
        /// <summary>The cashPnl property</summary>
        public double? CashPnl { get; set; }
        /// <summary>0x-prefixed 64-hex string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ConditionId { get; set; }
#nullable restore
#else
        public string ConditionId { get; set; }
#endif
        /// <summary>The currentValue property</summary>
        public double? CurrentValue { get; set; }
        /// <summary>The currPrice property</summary>
        public double? CurrPrice { get; set; }
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The outcome property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Outcome { get; set; }
#nullable restore
#else
        public string Outcome { get; set; }
#endif
        /// <summary>The outcomeIndex property</summary>
        public int? OutcomeIndex { get; set; }
        /// <summary>The profileImage property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProfileImage { get; set; }
#nullable restore
#else
        public string ProfileImage { get; set; }
#endif
        /// <summary>User Profile Address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProxyWallet { get; set; }
#nullable restore
#else
        public string ProxyWallet { get; set; }
#endif
        /// <summary>The realizedPnl property</summary>
        public double? RealizedPnl { get; set; }
        /// <summary>The size property</summary>
        public double? Size { get; set; }
        /// <summary>The totalBought property</summary>
        public double? TotalBought { get; set; }
        /// <summary>The totalPnl property</summary>
        public double? TotalPnl { get; set; }
        /// <summary>The verified property</summary>
        public bool? Verified { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.MarketPositionV1"/> and sets the default values.
        /// </summary>
        public MarketPositionV1()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.MarketPositionV1"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.MarketPositionV1 CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.MarketPositionV1();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "asset", n => { Asset = n.GetStringValue(); } },
                { "avgPrice", n => { AvgPrice = n.GetDoubleValue(); } },
                { "cashPnl", n => { CashPnl = n.GetDoubleValue(); } },
                { "conditionId", n => { ConditionId = n.GetStringValue(); } },
                { "currPrice", n => { CurrPrice = n.GetDoubleValue(); } },
                { "currentValue", n => { CurrentValue = n.GetDoubleValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "outcome", n => { Outcome = n.GetStringValue(); } },
                { "outcomeIndex", n => { OutcomeIndex = n.GetIntValue(); } },
                { "profileImage", n => { ProfileImage = n.GetStringValue(); } },
                { "proxyWallet", n => { ProxyWallet = n.GetStringValue(); } },
                { "realizedPnl", n => { RealizedPnl = n.GetDoubleValue(); } },
                { "size", n => { Size = n.GetDoubleValue(); } },
                { "totalBought", n => { TotalBought = n.GetDoubleValue(); } },
                { "totalPnl", n => { TotalPnl = n.GetDoubleValue(); } },
                { "verified", n => { Verified = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("asset", Asset);
            writer.WriteDoubleValue("avgPrice", AvgPrice);
            writer.WriteDoubleValue("cashPnl", CashPnl);
            writer.WriteStringValue("conditionId", ConditionId);
            writer.WriteDoubleValue("currentValue", CurrentValue);
            writer.WriteDoubleValue("currPrice", CurrPrice);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("outcome", Outcome);
            writer.WriteIntValue("outcomeIndex", OutcomeIndex);
            writer.WriteStringValue("profileImage", ProfileImage);
            writer.WriteStringValue("proxyWallet", ProxyWallet);
            writer.WriteDoubleValue("realizedPnl", RealizedPnl);
            writer.WriteDoubleValue("size", Size);
            writer.WriteDoubleValue("totalBought", TotalBought);
            writer.WriteDoubleValue("totalPnl", TotalPnl);
            writer.WriteBoolValue("verified", Verified);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
