// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ModifyOrdersCoidType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "modifyOrdersCOID")]
        #pragma warning disable CS1591
        ModifyOrdersCoid,
        #pragma warning restore CS1591
    }
}
