// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>
    /// A notification event for the user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Notification : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique identifier for the notification</summary>
        public int? Id { get; set; }
        /// <summary>API key of the notification owner (empty for broadcast notifications)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>Dynamic payload containing notification-specific data</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.NotificationPayloadProperty? Payload { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.NotificationPayloadProperty Payload { get; set; }
#endif
        /// <summary>Unix timestamp when the notification was created</summary>
        public int? Timestamp { get; set; }
        /// <summary>&quot;Type of notification:- 1: Order cancellation- 2: Order fill- 3: Market registered- 4: Market resolved- 5: Reward payout- 6: Child comment created&quot;</summary>
        public int? Type { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Notification"/> and sets the default values.
        /// </summary>
        public Notification()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Notification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Notification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Notification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "id", n => { Id = n.GetIntValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "payload", n => { Payload = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.NotificationPayloadProperty>(global::Soenneker.Polymarket.OpenApiClient.Models.NotificationPayloadProperty.CreateFromDiscriminatorValue); } },
                { "timestamp", n => { Timestamp = n.GetIntValue(); } },
                { "type", n => { Type = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("id", Id);
            writer.WriteStringValue("owner", Owner);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.NotificationPayloadProperty>("payload", Payload);
            writer.WriteIntValue("timestamp", Timestamp);
            writer.WriteIntValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
