// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum OpCancelAllType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "cancelAll")]
        #pragma warning disable CS1591
        CancelAll,
        #pragma warning restore CS1591
    }
}
