// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Order type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum OpenOrderOrderType
    {
        [EnumMember(Value = "GTC")]
        #pragma warning disable CS1591
        Gtc,
        #pragma warning restore CS1591
        [EnumMember(Value = "FOK")]
        #pragma warning disable CS1591
        Fok,
        #pragma warning restore CS1591
        [EnumMember(Value = "GTD")]
        #pragma warning disable CS1591
        Gtd,
        #pragma warning restore CS1591
        [EnumMember(Value = "FAK")]
        #pragma warning disable CS1591
        Fak,
        #pragma warning restore CS1591
    }
}
