// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Order : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Is buy</summary>
        public bool? Buy { get; set; }
        /// <summary>Client order ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Coid { get; set; }
#nullable restore
#else
        public string Coid { get; set; }
#endif
        /// <summary>Create timestamp in milliseconds</summary>
        public long? Cts { get; set; }
        /// <summary>Filled quantity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Fill { get; set; }
#nullable restore
#else
        public string Fill { get; set; }
#endif
        /// <summary>Instrument ID</summary>
        public int? Iid { get; set; }
        /// <summary>Order ID</summary>
        public int? Oid { get; set; }
        /// <summary>Price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? P { get; set; }
#nullable restore
#else
        public string P { get; set; }
#endif
        /// <summary>Post only</summary>
        public bool? Po { get; set; }
        /// <summary>Quantity in no. of contracts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Qty { get; set; }
#nullable restore
#else
        public string Qty { get; set; }
#endif
        /// <summary>Resting quantity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Rest { get; set; }
#nullable restore
#else
        public string Rest { get; set; }
#endif
        /// <summary>Reduce only</summary>
        public bool? Ro { get; set; }
        /// <summary>Order status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Time in force</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.Tif? Tif { get; set; }
        /// <summary>Update timestamp in milliseconds</summary>
        public long? Uts { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Order"/> and sets the default values.
        /// </summary>
        public Order()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Order"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Order CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Order();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buy", n => { Buy = n.GetBoolValue(); } },
                { "coid", n => { Coid = n.GetStringValue(); } },
                { "cts", n => { Cts = n.GetLongValue(); } },
                { "fill", n => { Fill = n.GetStringValue(); } },
                { "iid", n => { Iid = n.GetIntValue(); } },
                { "oid", n => { Oid = n.GetIntValue(); } },
                { "p", n => { P = n.GetStringValue(); } },
                { "po", n => { Po = n.GetBoolValue(); } },
                { "qty", n => { Qty = n.GetStringValue(); } },
                { "rest", n => { Rest = n.GetStringValue(); } },
                { "ro", n => { Ro = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tif", n => { Tif = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Tif>(); } },
                { "uts", n => { Uts = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("buy", Buy);
            writer.WriteStringValue("coid", Coid);
            writer.WriteLongValue("cts", Cts);
            writer.WriteStringValue("fill", Fill);
            writer.WriteIntValue("iid", Iid);
            writer.WriteIntValue("oid", Oid);
            writer.WriteStringValue("p", P);
            writer.WriteBoolValue("po", Po);
            writer.WriteStringValue("qty", Qty);
            writer.WriteStringValue("rest", Rest);
            writer.WriteBoolValue("ro", Ro);
            writer.WriteStringValue("status", Status);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Tif>("tif", Tif);
            writer.WriteLongValue("uts", Uts);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
