// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class OrderData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Is buy</summary>
        public bool? Buy { get; set; }
        /// <summary>Client order ID</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ClientOrderId { get; set; }
#nullable restore
#else
        public string ClientOrderId { get; set; }
#endif
        /// <summary>Create timestamp in milliseconds</summary>
        public long? CreatedTimestamp { get; set; }
        /// <summary>Filled quantity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FilledQuantity { get; set; }
#nullable restore
#else
        public string FilledQuantity { get; set; }
#endif
        /// <summary>Instrument ID</summary>
        public int? InstrumentId { get; set; }
        /// <summary>Order ID</summary>
        public int? OrderId { get; set; }
        /// <summary>Post only</summary>
        public bool? PostOnly { get; set; }
        /// <summary>Price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Price { get; set; }
#nullable restore
#else
        public string Price { get; set; }
#endif
        /// <summary>Quantity in no. of contracts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Quantity { get; set; }
#nullable restore
#else
        public string Quantity { get; set; }
#endif
        /// <summary>Resting quantity</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RestingQuantity { get; set; }
#nullable restore
#else
        public string RestingQuantity { get; set; }
#endif
        /// <summary>Reduce only</summary>
        public bool? Ro { get; set; }
        /// <summary>Order status</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>Time in force</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.Tif? Tif { get; set; }
        /// <summary>TP/SL-specific fields surfaced alongside the regular order shape.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.TpSlOrderFields? Tpsl { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.TpSlOrderFields Tpsl { get; set; }
#endif
        /// <summary>Update timestamp in milliseconds</summary>
        public long? UpdatedTimestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.OrderData"/> and sets the default values.
        /// </summary>
        public OrderData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.OrderData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.OrderData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.OrderData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "buy", n => { Buy = n.GetBoolValue(); } },
                { "client_order_id", n => { ClientOrderId = n.GetStringValue(); } },
                { "created_timestamp", n => { CreatedTimestamp = n.GetLongValue(); } },
                { "filled_quantity", n => { FilledQuantity = n.GetStringValue(); } },
                { "instrument_id", n => { InstrumentId = n.GetIntValue(); } },
                { "order_id", n => { OrderId = n.GetIntValue(); } },
                { "post_only", n => { PostOnly = n.GetBoolValue(); } },
                { "price", n => { Price = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetStringValue(); } },
                { "resting_quantity", n => { RestingQuantity = n.GetStringValue(); } },
                { "ro", n => { Ro = n.GetBoolValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
                { "tif", n => { Tif = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Tif>(); } },
                { "tpsl", n => { Tpsl = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.TpSlOrderFields>(global::Soenneker.Polymarket.OpenApiClient.Models.TpSlOrderFields.CreateFromDiscriminatorValue); } },
                { "updated_timestamp", n => { UpdatedTimestamp = n.GetLongValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("buy", Buy);
            writer.WriteStringValue("client_order_id", ClientOrderId);
            writer.WriteLongValue("created_timestamp", CreatedTimestamp);
            writer.WriteStringValue("filled_quantity", FilledQuantity);
            writer.WriteIntValue("instrument_id", InstrumentId);
            writer.WriteIntValue("order_id", OrderId);
            writer.WriteBoolValue("post_only", PostOnly);
            writer.WriteStringValue("price", Price);
            writer.WriteStringValue("quantity", Quantity);
            writer.WriteStringValue("resting_quantity", RestingQuantity);
            writer.WriteBoolValue("ro", Ro);
            writer.WriteStringValue("status", Status);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.Tif>("tif", Tif);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.TpSlOrderFields>("tpsl", Tpsl);
            writer.WriteLongValue("updated_timestamp", UpdatedTimestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
