// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Portfolio : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether the account is currently under liquidation</summary>
        public bool? InLiquidation { get; set; }
        /// <summary>The margin property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.MarginSummary? Margin { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.MarginSummary Margin { get; set; }
#endif
        /// <summary>The positions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition>? Positions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition> Positions { get; set; }
#endif
        /// <summary>Update timestamp in milliseconds</summary>
        public int? Timestamp { get; set; }
        /// <summary>Withdrawable balance in USD</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Withdrawable { get; set; }
#nullable restore
#else
        public string Withdrawable { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Portfolio"/> and sets the default values.
        /// </summary>
        public Portfolio()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Portfolio"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Portfolio CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Portfolio();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "in_liquidation", n => { InLiquidation = n.GetBoolValue(); } },
                { "margin", n => { Margin = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.MarginSummary>(global::Soenneker.Polymarket.OpenApiClient.Models.MarginSummary.CreateFromDiscriminatorValue); } },
                { "positions", n => { Positions = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition>(global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition.CreateFromDiscriminatorValue)?.AsList(); } },
                { "timestamp", n => { Timestamp = n.GetIntValue(); } },
                { "withdrawable", n => { Withdrawable = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("in_liquidation", InLiquidation);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.MarginSummary>("margin", Margin);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition>("positions", Positions);
            writer.WriteIntValue("timestamp", Timestamp);
            writer.WriteStringValue("withdrawable", Withdrawable);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
