// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PortfolioPosition : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Whether to use cross margin mode</summary>
        public bool? Cross { get; set; }
        /// <summary>Cumulative funding paid/received in USD</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CumulativeFunding { get; set; }
#nullable restore
#else
        public string CumulativeFunding { get; set; }
#endif
        /// <summary>Average entry price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EntryPrice { get; set; }
#nullable restore
#else
        public string EntryPrice { get; set; }
#endif
        /// <summary>&quot;Current collateral backing the position. For cross positions, this isthe required initial margin based on position size, mark price, theapplicable risk tier, and configured leverage. For isolated positions,this is the position&apos;s current equity: signed allocated margin plusunrealized PnL minus settled funding.The legacy `initial_margin` name is retained for API compatibility;`margin` would more accurately describe the field.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? InitialMargin { get; set; }
#nullable restore
#else
        public string InitialMargin { get; set; }
#endif
        /// <summary>Instrument ID</summary>
        public int? InstrumentId { get; set; }
        /// <summary>Leverage</summary>
        public int? Leverage { get; set; }
        /// <summary>Liquidation price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LiquidationPrice { get; set; }
#nullable restore
#else
        public string LiquidationPrice { get; set; }
#endif
        /// <summary>Maintenance margin amount</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MaintenanceMargin { get; set; }
#nullable restore
#else
        public string MaintenanceMargin { get; set; }
#endif
        /// <summary>Notional position value in USD</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PositionValue { get; set; }
#nullable restore
#else
        public string PositionValue { get; set; }
#endif
        /// <summary>Unrealized PnL divided by the position&apos;s current required initial margin, as a decimal.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReturnOnEquity { get; set; }
#nullable restore
#else
        public string ReturnOnEquity { get; set; }
#endif
        /// <summary>Signed position size in no. of contracts (positive = long, negative = short)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>Instrument symbol</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>Unrealized PnL in USD</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UnrealizedPnl { get; set; }
#nullable restore
#else
        public string UnrealizedPnl { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition"/> and sets the default values.
        /// </summary>
        public PortfolioPosition()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.PortfolioPosition();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cross", n => { Cross = n.GetBoolValue(); } },
                { "cumulative_funding", n => { CumulativeFunding = n.GetStringValue(); } },
                { "entry_price", n => { EntryPrice = n.GetStringValue(); } },
                { "initial_margin", n => { InitialMargin = n.GetStringValue(); } },
                { "instrument_id", n => { InstrumentId = n.GetIntValue(); } },
                { "leverage", n => { Leverage = n.GetIntValue(); } },
                { "liquidation_price", n => { LiquidationPrice = n.GetStringValue(); } },
                { "maintenance_margin", n => { MaintenanceMargin = n.GetStringValue(); } },
                { "position_value", n => { PositionValue = n.GetStringValue(); } },
                { "return_on_equity", n => { ReturnOnEquity = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "symbol", n => { Symbol = n.GetStringValue(); } },
                { "unrealized_pnl", n => { UnrealizedPnl = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("cross", Cross);
            writer.WriteStringValue("cumulative_funding", CumulativeFunding);
            writer.WriteStringValue("entry_price", EntryPrice);
            writer.WriteStringValue("initial_margin", InitialMargin);
            writer.WriteIntValue("instrument_id", InstrumentId);
            writer.WriteIntValue("leverage", Leverage);
            writer.WriteStringValue("liquidation_price", LiquidationPrice);
            writer.WriteStringValue("maintenance_margin", MaintenanceMargin);
            writer.WriteStringValue("position_value", PositionValue);
            writer.WriteStringValue("return_on_equity", ReturnOnEquity);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteStringValue("unrealized_pnl", UnrealizedPnl);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
