// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RelayerTransaction : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Timestamp when the transaction was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Encoded transaction data (0x-prefixed hex string)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Data { get; set; }
#nullable restore
#else
        public string Data { get; set; }
#endif
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>Transaction metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Metadata { get; set; }
#nullable restore
#else
        public string Metadata { get; set; }
#endif
        /// <summary>Transaction nonce</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Nonce { get; set; }
#nullable restore
#else
        public string Nonce { get; set; }
#endif
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProxyAddress { get; set; }
#nullable restore
#else
        public string ProxyAddress { get; set; }
#endif
        /// <summary>Transaction signature (0x-prefixed hex string)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Signature { get; set; }
#nullable restore
#else
        public string Signature { get; set; }
#endif
        /// <summary>Current state of the transaction</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionState? State { get; set; }
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? To { get; set; }
#nullable restore
#else
        public string To { get; set; }
#endif
        /// <summary>Onchain transaction hash (available once confirmed)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionHash { get; set; }
#nullable restore
#else
        public string TransactionHash { get; set; }
#endif
        /// <summary>Unique identifier for the transaction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionID { get; set; }
#nullable restore
#else
        public string TransactionID { get; set; }
#endif
        /// <summary>Transaction type</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionType? Type { get; set; }
        /// <summary>Timestamp when the transaction was last updated</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>Transaction value</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransaction"/> and sets the default values.
        /// </summary>
        public RelayerTransaction()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransaction"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransaction CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransaction();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "data", n => { Data = n.GetStringValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetStringValue(); } },
                { "nonce", n => { Nonce = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "proxyAddress", n => { ProxyAddress = n.GetStringValue(); } },
                { "signature", n => { Signature = n.GetStringValue(); } },
                { "state", n => { State = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionState>(); } },
                { "to", n => { To = n.GetStringValue(); } },
                { "transactionHash", n => { TransactionHash = n.GetStringValue(); } },
                { "transactionID", n => { TransactionID = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionType>(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("data", Data);
            writer.WriteStringValue("from", From);
            writer.WriteStringValue("metadata", Metadata);
            writer.WriteStringValue("nonce", Nonce);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("proxyAddress", ProxyAddress);
            writer.WriteStringValue("signature", Signature);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionState>("state", State);
            writer.WriteStringValue("to", To);
            writer.WriteStringValue("transactionHash", TransactionHash);
            writer.WriteStringValue("transactionID", TransactionID);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RelayerTransactionType>("type", Type);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
