// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>`notional` for requester BUY RFQs and `shares` for requester SELL RFQs.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum RequestedSizeUnit
    {
        [EnumMember(Value = "notional")]
        #pragma warning disable CS1591
        Notional,
        #pragma warning restore CS1591
        [EnumMember(Value = "shares")]
        #pragma warning disable CS1591
        Shares,
        #pragma warning restore CS1591
    }
}
