// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RevisionPayload : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>0x-prefixed 64-hex string</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuestionID { get; set; }
#nullable restore
#else
        public string QuestionID { get; set; }
#endif
        /// <summary>The revisions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.RevisionEntry>? Revisions { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.RevisionEntry> Revisions { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RevisionPayload"/> and sets the default values.
        /// </summary>
        public RevisionPayload()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RevisionPayload"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.RevisionPayload CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.RevisionPayload();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "questionID", n => { QuestionID = n.GetStringValue(); } },
                { "revisions", n => { Revisions = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.RevisionEntry>(global::Soenneker.Polymarket.OpenApiClient.Models.RevisionEntry.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("questionID", QuestionID);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.RevisionEntry>("revisions", Revisions);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
