// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>
    /// Point-in-time view of an RFQ and its competition/confirmation windows.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RfqSnapshot : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The selected executable bundle of maker allocations.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.FillBundle? Bundle { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.FillBundle Bundle { get; set; }
#endif
        /// <summary>Unix milliseconds.</summary>
        public long? CompetitionEndsAt { get; set; }
        /// <summary>Unix milliseconds.</summary>
        public long? CompetitionStartedAt { get; set; }
        /// <summary>Unix milliseconds.</summary>
        public long? ConfirmationEndsAt { get; set; }
        /// <summary>Unix milliseconds.</summary>
        public long? ConfirmationStartedAt { get; set; }
        /// <summary>The maker_confirmations property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationSnapshot>? MakerConfirmations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationSnapshot> MakerConfirmations { get; set; }
#endif
        /// <summary>The quote_id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? QuoteId { get; set; }
#nullable restore
#else
        public string QuoteId { get; set; }
#endif
        /// <summary>The RFQ request as stored by the engine.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.RfqRequest? Request { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.RfqRequest Request { get; set; }
#endif
        /// <summary>Lifecycle status of the RFQ</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Models.RfqStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot"/> and sets the default values.
        /// </summary>
        public RfqSnapshot()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.RfqSnapshot();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bundle", n => { Bundle = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.FillBundle>(global::Soenneker.Polymarket.OpenApiClient.Models.FillBundle.CreateFromDiscriminatorValue); } },
                { "competition_ends_at", n => { CompetitionEndsAt = n.GetLongValue(); } },
                { "competition_started_at", n => { CompetitionStartedAt = n.GetLongValue(); } },
                { "confirmation_ends_at", n => { ConfirmationEndsAt = n.GetLongValue(); } },
                { "confirmation_started_at", n => { ConfirmationStartedAt = n.GetLongValue(); } },
                { "maker_confirmations", n => { MakerConfirmations = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationSnapshot>(global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationSnapshot.CreateFromDiscriminatorValue)?.AsList(); } },
                { "quote_id", n => { QuoteId = n.GetStringValue(); } },
                { "request", n => { Request = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqRequest>(global::Soenneker.Polymarket.OpenApiClient.Models.RfqRequest.CreateFromDiscriminatorValue); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.FillBundle>("bundle", Bundle);
            writer.WriteLongValue("competition_ends_at", CompetitionEndsAt);
            writer.WriteLongValue("competition_started_at", CompetitionStartedAt);
            writer.WriteLongValue("confirmation_ends_at", ConfirmationEndsAt);
            writer.WriteLongValue("confirmation_started_at", ConfirmationStartedAt);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.MakerConfirmationSnapshot>("maker_confirmations", MakerConfirmations);
            writer.WriteStringValue("quote_id", QuoteId);
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqRequest>("request", Request);
            writer.WriteEnumValue<global::Soenneker.Polymarket.OpenApiClient.Models.RfqStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
