// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Status of the order after processing</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SendOrderResponseStatus
    {
        [EnumMember(Value = "live")]
        #pragma warning disable CS1591
        Live,
        #pragma warning restore CS1591
        [EnumMember(Value = "matched")]
        #pragma warning disable CS1591
        Matched,
        #pragma warning restore CS1591
        [EnumMember(Value = "delayed")]
        #pragma warning disable CS1591
        Delayed,
        #pragma warning restore CS1591
    }
}
