// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Series : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The active property</summary>
        public bool? Active { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archived property</summary>
        public bool? Archived { get; set; }
        /// <summary>The categories property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Category2>? Categories { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Category2> Categories { get; set; }
#endif
        /// <summary>The cgAssetName property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CgAssetName { get; set; }
#nullable restore
#else
        public string CgAssetName { get; set; }
#endif
        /// <summary>The chats property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Chat>? Chats { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Chat> Chats { get; set; }
#endif
        /// <summary>The closed property</summary>
        public bool? Closed { get; set; }
        /// <summary>The collections property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Collection>? Collections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Collection> Collections { get; set; }
#endif
        /// <summary>The commentCount property</summary>
        public int? CommentCount { get; set; }
        /// <summary>The commentsEnabled property</summary>
        public bool? CommentsEnabled { get; set; }
        /// <summary>The competitive property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Competitive { get; set; }
#nullable restore
#else
        public string Competitive { get; set; }
#endif
        /// <summary>The createdAt property</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The createdBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CreatedBy { get; set; }
#nullable restore
#else
        public string CreatedBy { get; set; }
#endif
        /// <summary>The description property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The events property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.EventType>? Events { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.EventType> Events { get; set; }
#endif
        /// <summary>The featured property</summary>
        public bool? Featured { get; set; }
        /// <summary>The icon property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Icon { get; set; }
#nullable restore
#else
        public string Icon { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The image property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Image { get; set; }
#nullable restore
#else
        public string Image { get; set; }
#endif
        /// <summary>The isTemplate property</summary>
        public bool? IsTemplate { get; set; }
        /// <summary>The layout property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Layout { get; set; }
#nullable restore
#else
        public string Layout { get; set; }
#endif
        /// <summary>The liquidity property</summary>
        public double? Liquidity { get; set; }
        /// <summary>The new property</summary>
        public bool? New { get; set; }
        /// <summary>The publishedAt property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PublishedAt { get; set; }
#nullable restore
#else
        public string PublishedAt { get; set; }
#endif
        /// <summary>The pythTokenID property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PythTokenID { get; set; }
#nullable restore
#else
        public string PythTokenID { get; set; }
#endif
        /// <summary>The recurrence property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Recurrence { get; set; }
#nullable restore
#else
        public string Recurrence { get; set; }
#endif
        /// <summary>The restricted property</summary>
        public bool? Restricted { get; set; }
        /// <summary>The score property</summary>
        public int? Score { get; set; }
        /// <summary>The seriesType property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SeriesType { get; set; }
#nullable restore
#else
        public string SeriesType { get; set; }
#endif
        /// <summary>The slug property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Slug { get; set; }
#nullable restore
#else
        public string Slug { get; set; }
#endif
        /// <summary>The startDate property</summary>
        public DateTimeOffset? StartDate { get; set; }
        /// <summary>The subtitle property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subtitle { get; set; }
#nullable restore
#else
        public string Subtitle { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Tag>? Tags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Polymarket.OpenApiClient.Models.Tag> Tags { get; set; }
#endif
        /// <summary>The templateVariables property</summary>
        public bool? TemplateVariables { get; set; }
        /// <summary>The ticker property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ticker { get; set; }
#nullable restore
#else
        public string Ticker { get; set; }
#endif
        /// <summary>The title property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Title { get; set; }
#nullable restore
#else
        public string Title { get; set; }
#endif
        /// <summary>The updatedAt property</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The updatedBy property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UpdatedBy { get; set; }
#nullable restore
#else
        public string UpdatedBy { get; set; }
#endif
        /// <summary>The volume property</summary>
        public double? Volume { get; set; }
        /// <summary>The volume24hr property</summary>
        public double? Volume24hr { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Series"/> and sets the default values.
        /// </summary>
        public Series()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Series"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Series CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Series();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "active", n => { Active = n.GetBoolValue(); } },
                { "archived", n => { Archived = n.GetBoolValue(); } },
                { "categories", n => { Categories = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Category2>(global::Soenneker.Polymarket.OpenApiClient.Models.Category2.CreateFromDiscriminatorValue)?.AsList(); } },
                { "cgAssetName", n => { CgAssetName = n.GetStringValue(); } },
                { "chats", n => { Chats = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Chat>(global::Soenneker.Polymarket.OpenApiClient.Models.Chat.CreateFromDiscriminatorValue)?.AsList(); } },
                { "closed", n => { Closed = n.GetBoolValue(); } },
                { "collections", n => { Collections = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Collection>(global::Soenneker.Polymarket.OpenApiClient.Models.Collection.CreateFromDiscriminatorValue)?.AsList(); } },
                { "commentCount", n => { CommentCount = n.GetIntValue(); } },
                { "commentsEnabled", n => { CommentsEnabled = n.GetBoolValue(); } },
                { "competitive", n => { Competitive = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "createdBy", n => { CreatedBy = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "events", n => { Events = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.EventType>(global::Soenneker.Polymarket.OpenApiClient.Models.EventType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "featured", n => { Featured = n.GetBoolValue(); } },
                { "icon", n => { Icon = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "image", n => { Image = n.GetStringValue(); } },
                { "isTemplate", n => { IsTemplate = n.GetBoolValue(); } },
                { "layout", n => { Layout = n.GetStringValue(); } },
                { "liquidity", n => { Liquidity = n.GetDoubleValue(); } },
                { "new", n => { New = n.GetBoolValue(); } },
                { "publishedAt", n => { PublishedAt = n.GetStringValue(); } },
                { "pythTokenID", n => { PythTokenID = n.GetStringValue(); } },
                { "recurrence", n => { Recurrence = n.GetStringValue(); } },
                { "restricted", n => { Restricted = n.GetBoolValue(); } },
                { "score", n => { Score = n.GetIntValue(); } },
                { "seriesType", n => { SeriesType = n.GetStringValue(); } },
                { "slug", n => { Slug = n.GetStringValue(); } },
                { "startDate", n => { StartDate = n.GetDateTimeOffsetValue(); } },
                { "subtitle", n => { Subtitle = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Tag>(global::Soenneker.Polymarket.OpenApiClient.Models.Tag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "templateVariables", n => { TemplateVariables = n.GetBoolValue(); } },
                { "ticker", n => { Ticker = n.GetStringValue(); } },
                { "title", n => { Title = n.GetStringValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "updatedBy", n => { UpdatedBy = n.GetStringValue(); } },
                { "volume", n => { Volume = n.GetDoubleValue(); } },
                { "volume24hr", n => { Volume24hr = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("active", Active);
            writer.WriteBoolValue("archived", Archived);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Category2>("categories", Categories);
            writer.WriteStringValue("cgAssetName", CgAssetName);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Chat>("chats", Chats);
            writer.WriteBoolValue("closed", Closed);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Collection>("collections", Collections);
            writer.WriteIntValue("commentCount", CommentCount);
            writer.WriteBoolValue("commentsEnabled", CommentsEnabled);
            writer.WriteStringValue("competitive", Competitive);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("createdBy", CreatedBy);
            writer.WriteStringValue("description", Description);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.EventType>("events", Events);
            writer.WriteBoolValue("featured", Featured);
            writer.WriteStringValue("icon", Icon);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("image", Image);
            writer.WriteBoolValue("isTemplate", IsTemplate);
            writer.WriteStringValue("layout", Layout);
            writer.WriteDoubleValue("liquidity", Liquidity);
            writer.WriteBoolValue("new", New);
            writer.WriteStringValue("publishedAt", PublishedAt);
            writer.WriteStringValue("pythTokenID", PythTokenID);
            writer.WriteStringValue("recurrence", Recurrence);
            writer.WriteBoolValue("restricted", Restricted);
            writer.WriteIntValue("score", Score);
            writer.WriteStringValue("seriesType", SeriesType);
            writer.WriteStringValue("slug", Slug);
            writer.WriteDateTimeOffsetValue("startDate", StartDate);
            writer.WriteStringValue("subtitle", Subtitle);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Polymarket.OpenApiClient.Models.Tag>("tags", Tags);
            writer.WriteBoolValue("templateVariables", TemplateVariables);
            writer.WriteStringValue("ticker", Ticker);
            writer.WriteStringValue("title", Title);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteStringValue("updatedBy", UpdatedBy);
            writer.WriteDoubleValue("volume", Volume);
            writer.WriteDoubleValue("volume24hr", Volume24hr);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
