// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SignatureParams : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Base gas</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BaseGas { get; set; }
#nullable restore
#else
        public string BaseGas { get; set; }
#endif
        /// <summary>Gas price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GasPrice { get; set; }
#nullable restore
#else
        public string GasPrice { get; set; }
#endif
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GasToken { get; set; }
#nullable restore
#else
        public string GasToken { get; set; }
#endif
        /// <summary>Operation type</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Operation { get; set; }
#nullable restore
#else
        public string Operation { get; set; }
#endif
        /// <summary>Ethereum address (0x-prefixed, 40 hex chars)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RefundReceiver { get; set; }
#nullable restore
#else
        public string RefundReceiver { get; set; }
#endif
        /// <summary>Safe transaction gas</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SafeTxnGas { get; set; }
#nullable restore
#else
        public string SafeTxnGas { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.SignatureParams"/> and sets the default values.
        /// </summary>
        public SignatureParams()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.SignatureParams"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.SignatureParams CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.SignatureParams();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "baseGas", n => { BaseGas = n.GetStringValue(); } },
                { "gasPrice", n => { GasPrice = n.GetStringValue(); } },
                { "gasToken", n => { GasToken = n.GetStringValue(); } },
                { "operation", n => { Operation = n.GetStringValue(); } },
                { "refundReceiver", n => { RefundReceiver = n.GetStringValue(); } },
                { "safeTxnGas", n => { SafeTxnGas = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("baseGas", BaseGas);
            writer.WriteStringValue("gasPrice", GasPrice);
            writer.WriteStringValue("gasToken", GasToken);
            writer.WriteStringValue("operation", Operation);
            writer.WriteStringValue("refundReceiver", RefundReceiver);
            writer.WriteStringValue("safeTxnGas", SafeTxnGas);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
