// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>Transaction type</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubmitRequestType
    {
        [EnumMember(Value = "SAFE")]
        #pragma warning disable CS1591
        Safe,
        #pragma warning restore CS1591
        [EnumMember(Value = "PROXY")]
        #pragma warning disable CS1591
        Proxy,
        #pragma warning restore CS1591
    }
}
