// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Ticker : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The funding_rate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Polymarket.OpenApiClient.Models.FundingRate2? FundingRate { get; set; }
#nullable restore
#else
        public global::Soenneker.Polymarket.OpenApiClient.Models.FundingRate2 FundingRate { get; set; }
#endif
        /// <summary>Index price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IndexPrice { get; set; }
#nullable restore
#else
        public string IndexPrice { get; set; }
#endif
        /// <summary>Instrument ID</summary>
        public int? InstrumentId { get; set; }
        /// <summary>Last traded price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastPrice { get; set; }
#nullable restore
#else
        public string LastPrice { get; set; }
#endif
        /// <summary>Mark price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MarkPrice { get; set; }
#nullable restore
#else
        public string MarkPrice { get; set; }
#endif
        /// <summary>Mid price</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MidPrice { get; set; }
#nullable restore
#else
        public string MidPrice { get; set; }
#endif
        /// <summary>Next funding timestamp in milliseconds</summary>
        public int? NextFunding { get; set; }
        /// <summary>Open interest in number of contracts</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OpenInterest { get; set; }
#nullable restore
#else
        public string OpenInterest { get; set; }
#endif
        /// <summary>Instrument symbol</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Symbol { get; set; }
#nullable restore
#else
        public string Symbol { get; set; }
#endif
        /// <summary>Timestamp in milliseconds</summary>
        public int? Timestamp { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Ticker"/> and sets the default values.
        /// </summary>
        public Ticker()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Ticker"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Polymarket.OpenApiClient.Models.Ticker CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Polymarket.OpenApiClient.Models.Ticker();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "funding_rate", n => { FundingRate = n.GetObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.FundingRate2>(global::Soenneker.Polymarket.OpenApiClient.Models.FundingRate2.CreateFromDiscriminatorValue); } },
                { "index_price", n => { IndexPrice = n.GetStringValue(); } },
                { "instrument_id", n => { InstrumentId = n.GetIntValue(); } },
                { "last_price", n => { LastPrice = n.GetStringValue(); } },
                { "mark_price", n => { MarkPrice = n.GetStringValue(); } },
                { "mid_price", n => { MidPrice = n.GetStringValue(); } },
                { "next_funding", n => { NextFunding = n.GetIntValue(); } },
                { "open_interest", n => { OpenInterest = n.GetStringValue(); } },
                { "symbol", n => { Symbol = n.GetStringValue(); } },
                { "timestamp", n => { Timestamp = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Polymarket.OpenApiClient.Models.FundingRate2>("funding_rate", FundingRate);
            writer.WriteStringValue("index_price", IndexPrice);
            writer.WriteIntValue("instrument_id", InstrumentId);
            writer.WriteStringValue("last_price", LastPrice);
            writer.WriteStringValue("mark_price", MarkPrice);
            writer.WriteStringValue("mid_price", MidPrice);
            writer.WriteIntValue("next_funding", NextFunding);
            writer.WriteStringValue("open_interest", OpenInterest);
            writer.WriteStringValue("symbol", Symbol);
            writer.WriteIntValue("timestamp", Timestamp);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
