// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Models
{
    /// <summary>How the conditional order sizes itself.- `order` - child of a parent entry (bracket / OCO ladder). Quantity is required.- `position` - attached to an open position. v1 always closes the full position (`qty` must be `&quot;0&quot;`).</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TrScope
    {
        [EnumMember(Value = "order")]
        #pragma warning disable CS1591
        Order,
        #pragma warning restore CS1591
        [EnumMember(Value = "position")]
        #pragma warning disable CS1591
        Position,
        #pragma warning restore CS1591
    }
}
