// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Relayer.Nonce
{
    /// <summary>
    /// Builds and executes requests for operations under \relayer\nonce
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class NonceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NonceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/relayer/nonce?address={address}&type={type}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public NonceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/relayer/nonce?address={address}&type={type}", rawUrl)
        {
        }
        /// <summary>
        /// Gets the current Proxy or Safe nonce for a user. Takes in the user&apos;s signer address and the type of nonce to retrieve.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.NonceResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.RelayerErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.RelayerErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.NonceResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder.NonceRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.NonceResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder.NonceRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.RelayerErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.RelayerErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.NonceResponse>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.NonceResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Gets the current Proxy or Safe nonce for a user. Takes in the user&apos;s signer address and the type of nonce to retrieve.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder.NonceRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder.NonceRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Relayer.Nonce.NonceRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Gets the current Proxy or Safe nonce for a user. Takes in the user&apos;s signer address and the type of nonce to retrieve.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class NonceRequestBuilderGetQueryParameters 
        {
            /// <summary>User&apos;s signer address</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("address")]
            public string? Address { get; set; }
#nullable restore
#else
            [QueryParameter("address")]
            public string Address { get; set; }
#endif
            /// <summary>Type of nonce to retrieve</summary>
            [QueryParameter("type")]
            public global::Soenneker.Polymarket.OpenApiClient.Models.RelayerGetNonceTypeParameter? Type { get; set; }
        }
    }
}
#pragma warning restore CS0618
