// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets;
using Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Clob.Rewards
{
    /// <summary>
    /// Builds and executes requests for operations under \clob\rewards
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class RewardsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The markets property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.MarketsRequestBuilder Markets
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.MarketsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The user property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder User
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.RewardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RewardsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.RewardsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public RewardsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
