// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Bridge.Status.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Bridge.Status
{
    /// <summary>
    /// Builds and executes requests for operations under \bridge\status
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StatusRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Polymarket.OpenApiClient.bridge.status.item collection</summary>
        /// <param name="position">The bridge address to query for transaction status, taken from the `/deposit` or `/withdraw` response. EVM, Solana, Tron, and Bitcoin address formats are supported. EVM addresses are normalized before the request is forwarded upstream.</param>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Bridge.Status.Item.WithAddressItemRequestBuilder"/></returns>
        public global::Soenneker.Polymarket.OpenApiClient.Bridge.Status.Item.WithAddressItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("address", position);
                return new global::Soenneker.Polymarket.OpenApiClient.Bridge.Status.Item.WithAddressItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Bridge.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bridge/status", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Bridge.Status.StatusRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StatusRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/bridge/status", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
