// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\account\withdrawals
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithdrawalsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithdrawalsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/withdrawals{?end_timestamp*,hash*,start_timestamp*,withdrawal_status*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithdrawalsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/withdrawals{?end_timestamp*,hash*,start_timestamp*,withdrawal_status*}", rawUrl)
        {
        }
        /// <summary>
        /// Get withdrawal history for the authenticated account.If no end time is provided, the current time will be used.Maximum of 100 entries returned per request.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.Withdrawals"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.Withdrawals?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder.WithdrawalsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.Withdrawals> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder.WithdrawalsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.Error400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Polymarket.OpenApiClient.Models.Error401.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Polymarket.OpenApiClient.Models.Error429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.Error500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.Withdrawals>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.Withdrawals.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get withdrawal history for the authenticated account.If no end time is provided, the current time will be used.Maximum of 100 entries returned per request.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder.WithdrawalsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder.WithdrawalsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Withdrawals.WithdrawalsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get withdrawal history for the authenticated account.If no end time is provided, the current time will be used.Maximum of 100 entries returned per request.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class WithdrawalsRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("end_timestamp")]
            public string? EndTimestamp { get; set; }
#nullable restore
#else
            [QueryParameter("end_timestamp")]
            public string EndTimestamp { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("hash")]
            public string? Hash { get; set; }
#nullable restore
#else
            [QueryParameter("hash")]
            public string Hash { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("start_timestamp")]
            public string? StartTimestamp { get; set; }
#nullable restore
#else
            [QueryParameter("start_timestamp")]
            public string StartTimestamp { get; set; }
#endif
            [QueryParameter("withdrawal_status")]
            public global::Soenneker.Polymarket.OpenApiClient.Models.WithdrawalStatus? WithdrawalStatus { get; set; }
        }
    }
}
#pragma warning restore CS0618
