// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\account\equity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EquityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EquityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/equity?interval={interval}&start_timestamp={start_timestamp}{&end_timestamp*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EquityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/account/equity?interval={interval}&start_timestamp={start_timestamp}{&end_timestamp*}", rawUrl)
        {
        }
        /// <summary>
        /// Get equity history for the authenticated account.If no end time is provided, the current time will be used.Each point is the last equity sample in its `interval` bucket, stamped withthat sample&apos;s own timestamp rather than the bucket&apos;s start — so everytimestamp falls within the requested window. Buckets are aligned to theUnix epoch.Equity history is served at one-minute resolution, so `1s` is served as`1m`.Maximum of 1000 entries returned per request — of buckets, so a coarserinterval covers a longer window before `more` is set. When `more` is true,page by re-requesting from one millisecond past the last timestampreturned; that always lands on the next bucket, never back inside the onejust served.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.EquityHistory"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error401">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.EquityHistory?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder.EquityRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.EquityHistory> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder.EquityRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.Error400.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Polymarket.OpenApiClient.Models.Error401.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Polymarket.OpenApiClient.Models.Error429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.Error500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.EquityHistory>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.EquityHistory.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get equity history for the authenticated account.If no end time is provided, the current time will be used.Each point is the last equity sample in its `interval` bucket, stamped withthat sample&apos;s own timestamp rather than the bucket&apos;s start — so everytimestamp falls within the requested window. Buckets are aligned to theUnix epoch.Equity history is served at one-minute resolution, so `1s` is served as`1m`.Maximum of 1000 entries returned per request — of buckets, so a coarserinterval covers a longer window before `more` is set. When `more` is true,page by re-requesting from one millisecond past the last timestampreturned; that always lands on the next bucket, never back inside the onejust served.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder.EquityRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder.EquityRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Account.Equity.EquityRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get equity history for the authenticated account.If no end time is provided, the current time will be used.Each point is the last equity sample in its `interval` bucket, stamped withthat sample&apos;s own timestamp rather than the bucket&apos;s start — so everytimestamp falls within the requested window. Buckets are aligned to theUnix epoch.Equity history is served at one-minute resolution, so `1s` is served as`1m`.Maximum of 1000 entries returned per request — of buckets, so a coarserinterval covers a longer window before `more` is set. When `more` is true,page by re-requesting from one millisecond past the last timestampreturned; that always lands on the next bucket, never back inside the onejust served.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EquityRequestBuilderGetQueryParameters 
        {
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("end_timestamp")]
            public string? EndTimestamp { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("end_timestamp")]
            public string EndTimestamp { get; set; }
            #pragma warning restore CS1591
#endif
            #pragma warning disable CS1591
            [QueryParameter("interval")]
            public global::Soenneker.Polymarket.OpenApiClient.Models.Interval? Interval { get; set; }
            #pragma warning restore CS1591
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            #pragma warning disable CS1591
            [QueryParameter("start_timestamp")]
            public string? StartTimestamp { get; set; }
            #pragma warning restore CS1591
#nullable restore
#else
            #pragma warning disable CS1591
            [QueryParameter("start_timestamp")]
            public string StartTimestamp { get; set; }
            #pragma warning restore CS1591
#endif
        }
    }
}
#pragma warning restore CS0618
