// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Assets;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Bbo;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Book;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Exchange;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Fees;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Funding;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.IndexNamespace;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Instruments;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Invite;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Klines;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.LimitTiers;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.MarkHistory;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Ping;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Portfolio;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.PositionFills;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Statistics;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Tickers;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Time;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Trades;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Info
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\info
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class InfoRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The assets property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Assets.AssetsRequestBuilder Assets
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Assets.AssetsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The bbo property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Bbo.BboRequestBuilder Bbo
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Bbo.BboRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The book property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Book.BookRequestBuilder Book
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Book.BookRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The exchange property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Exchange.ExchangeRequestBuilder Exchange
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Exchange.ExchangeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The fees property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Fees.FeesRequestBuilder Fees
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Fees.FeesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The funding property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Funding.FundingRequestBuilder Funding
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Funding.FundingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The index property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.IndexNamespace.IndexRequestBuilder Index
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.IndexNamespace.IndexRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The instruments property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Instruments.InstrumentsRequestBuilder Instruments
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Instruments.InstrumentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The invite property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Invite.InviteRequestBuilder Invite
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Invite.InviteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The klines property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Klines.KlinesRequestBuilder Klines
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Klines.KlinesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The limitTiers property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.LimitTiers.LimitTiersRequestBuilder LimitTiers
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.LimitTiers.LimitTiersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The markHistory property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.MarkHistory.MarkHistoryRequestBuilder MarkHistory
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.MarkHistory.MarkHistoryRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ping property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Ping.PingRequestBuilder Ping
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Ping.PingRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The portfolio property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Portfolio.PortfolioRequestBuilder Portfolio
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Portfolio.PortfolioRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The positionFills property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.PositionFills.PositionFillsRequestBuilder PositionFills
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.PositionFills.PositionFillsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The statistics property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Statistics.StatisticsRequestBuilder Statistics
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Statistics.StatisticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tickers property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Tickers.TickersRequestBuilder Tickers
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Tickers.TickersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The time property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Time.TimeRequestBuilder Time
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Time.TimeRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trades property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Trades.TradesRequestBuilder Trades
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.Trades.TradesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/info", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Info.InfoRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public InfoRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/info", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
