// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi
{
    /// <summary>
    /// Builds and executes requests for operations under \clob\rewards\markets\multi
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MultiRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MultiRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards/markets/multi{?event_id*,event_title*,max_price*,max_spread*,max_volume_24hr*,min_price*,min_spread*,min_volume_24hr*,next_cursor*,order_by*,page_size*,position*,q*,tag_slug*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MultiRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards/markets/multi{?event_id*,event_title*,max_price*,max_spread*,max_volume_24hr*,min_price*,min_spread*,min_volume_24hr*,next_cursor*,order_by*,page_size*,position*,q*,tag_slug*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns a list of active markets with their reward configurations.Supports text search, tag filtering, numeric filters, and sorting.Results are paginated (100 items per page by default). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedMultiMarketInfo"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedMultiMarketInfo?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder.MultiRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedMultiMarketInfo> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder.MultiRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedMultiMarketInfo>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedMultiMarketInfo.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns a list of active markets with their reward configurations.Supports text search, tag filtering, numeric filters, and sorting.Results are paginated (100 items per page by default). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder.MultiRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder.MultiRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.Markets.Multi.MultiRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns a list of active markets with their reward configurations.Supports text search, tag filtering, numeric filters, and sorting.Results are paginated (100 items per page by default). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class MultiRequestBuilderGetQueryParameters 
        {
            /// <summary>Filter by event ID. Can be repeated for multiple events (e.g., ?event_id=100&amp;event_id=200)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event_id")]
            public string? EventId { get; set; }
#nullable restore
#else
            [QueryParameter("event_id")]
            public string EventId { get; set; }
#endif
            /// <summary>Search event titles using case-insensitive pattern matching</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("event_title")]
            public string? EventTitle { get; set; }
#nullable restore
#else
            [QueryParameter("event_title")]
            public string EventTitle { get; set; }
#endif
            /// <summary>Maximum first token price filter</summary>
            [QueryParameter("max_price")]
            public double? MaxPrice { get; set; }
            /// <summary>Maximum spread filter</summary>
            [QueryParameter("max_spread")]
            public double? MaxSpread { get; set; }
            /// <summary>Maximum 24-hour volume filter</summary>
            [QueryParameter("max_volume_24hr")]
            public double? MaxVolume24hr { get; set; }
            /// <summary>Minimum first token price filter</summary>
            [QueryParameter("min_price")]
            public double? MinPrice { get; set; }
            /// <summary>Minimum spread filter</summary>
            [QueryParameter("min_spread")]
            public double? MinSpread { get; set; }
            /// <summary>Minimum 24-hour volume filter</summary>
            [QueryParameter("min_volume_24hr")]
            public double? MinVolume24hr { get; set; }
            /// <summary>Pagination cursor from previous response</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("next_cursor")]
            public string? NextCursor { get; set; }
#nullable restore
#else
            [QueryParameter("next_cursor")]
            public string NextCursor { get; set; }
#endif
            /// <summary>Field to sort results by</summary>
            [QueryParameter("order_by")]
            public global::Soenneker.Polymarket.OpenApiClient.Models.ClobGetMultiMarketsOrderByParameter? OrderBy { get; set; }
            /// <summary>Number of items per page (max 500, values above are capped)</summary>
            [QueryParameter("page_size")]
            public int? PageSize { get; set; }
            /// <summary>Sort direction</summary>
            [QueryParameter("position")]
            public global::Soenneker.Polymarket.OpenApiClient.Models.ClobGetMultiMarketsPositionParameter? Position { get; set; }
            /// <summary>Text search on market question/description</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("q")]
            public string? Q { get; set; }
#nullable restore
#else
            [QueryParameter("q")]
            public string Q { get; set; }
#endif
            /// <summary>Filter by tag slug. Can be repeated for OR logic (e.g., ?tag_slug=sports&amp;tag_slug=politics)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag_slug")]
            public string? TagSlug { get; set; }
#nullable restore
#else
            [QueryParameter("tag_slug")]
            public string TagSlug { get; set; }
#endif
        }
    }
}
#pragma warning restore CS0618
