// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Data.V1.Activity.Combos;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Data.V1.Activity
{
    /// <summary>
    /// Builds and executes requests for operations under \data\v1\activity
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ActivityRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The combos property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Data.V1.Activity.Combos.CombosRequestBuilder Combos
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Data.V1.Activity.Combos.CombosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Data.V1.Activity.ActivityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/v1/activity", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Data.V1.Activity.ActivityRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ActivityRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/data/v1/activity", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
