// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Markets;
using Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Percentages;
using Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Total;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User
{
    /// <summary>
    /// Builds and executes requests for operations under \clob\rewards\user
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class UserRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The markets property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Markets.MarketsRequestBuilder Markets
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Markets.MarketsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The percentages property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Percentages.PercentagesRequestBuilder Percentages
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Percentages.PercentagesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The total property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Total.TotalRequestBuilder Total
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.Total.TotalRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards/user?date={date}{&maker_address*,next_cursor*,signature_type*,sponsored*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public UserRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/clob/rewards/user?date={date}{&maker_address*,next_cursor*,signature_type*,sponsored*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns an array of user earnings per market for a provided day.Requires CLOB L2 Auth headers.Results are paginated (100 items per page). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedUserEarnings"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedUserEarnings?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder.UserRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedUserEarnings> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder.UserRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.ClobErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedUserEarnings>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.PaginatedUserEarnings.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns an array of user earnings per market for a provided day.Requires CLOB L2 Auth headers.Results are paginated (100 items per page). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder.UserRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder.UserRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Clob.Rewards.User.UserRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns an array of user earnings per market for a provided day.Requires CLOB L2 Auth headers.Results are paginated (100 items per page). Use next_cursor to fetch subsequent pages.A next_cursor value of &quot;LTE=&quot; indicates the last page.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class UserRequestBuilderGetQueryParameters 
        {
            /// <summary>Date in YYYY-MM-DD format</summary>
            [QueryParameter("date")]
            public Date? Date { get; set; }
            /// <summary>Maker address to query earnings for</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("maker_address")]
            public string? MakerAddress { get; set; }
#nullable restore
#else
            [QueryParameter("maker_address")]
            public string MakerAddress { get; set; }
#endif
            /// <summary>Pagination cursor from previous response</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("next_cursor")]
            public string? NextCursor { get; set; }
#nullable restore
#else
            [QueryParameter("next_cursor")]
            public string NextCursor { get; set; }
#endif
            /// <summary>Signature type for address derivation (required for API KEY auth):- 0: EOA- 1: POLY_PROXY- 2: POLY_GNOSIS_SAFE</summary>
            [QueryParameter("signature_type")]
            public int? SignatureType { get; set; }
            /// <summary>If true, returns sponsored-only earnings</summary>
            [QueryParameter("sponsored")]
            public bool? Sponsored { get; set; }
        }
    }
}
#pragma warning restore CS0618
