// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Leverage;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Margin;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Orders;
using Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.OrdersCoid;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\trade
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TradeRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The autoCancel property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder AutoCancel
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The leverage property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Leverage.LeverageRequestBuilder Leverage
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Leverage.LeverageRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The margin property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Margin.MarginRequestBuilder Margin
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Margin.MarginRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The orders property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Orders.OrdersRequestBuilder Orders
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.Orders.OrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The ordersCoid property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.OrdersCoid.OrdersCoidRequestBuilder OrdersCoid
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.OrdersCoid.OrdersCoidRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.TradeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TradeRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/trade", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.TradeRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TradeRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/trade", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
