// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Comments;
using Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Tags;
using Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.TweetCount;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \gamma\events\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EventsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The comments property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Comments.CommentsRequestBuilder Comments
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Comments.CommentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tags property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Tags.TagsRequestBuilder Tags
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.Tags.TagsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The tweetCount property</summary>
        public global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.TweetCount.TweetCountRequestBuilder TweetCount
        {
            get => new global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.TweetCount.TweetCountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gamma/events/{id}{?include_chat*,include_template*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public EventsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gamma/events/{id}{?include_chat*,include_template*}", rawUrl)
        {
        }
        /// <summary>
        /// Get event by id
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.EventType"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.EventType?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder.EventsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.EventType> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder.EventsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.EventType>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.EventType.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get event by id
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder.EventsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder.EventsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Item.EventsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get event by id
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class EventsItemRequestBuilderGetQueryParameters 
        {
            #pragma warning disable CS1591
            [QueryParameter("include_chat")]
            public bool? IncludeChat { get; set; }
            #pragma warning restore CS1591
            #pragma warning disable CS1591
            [QueryParameter("include_template")]
            public bool? IncludeTemplate { get; set; }
            #pragma warning restore CS1591
        }
    }
}
#pragma warning restore CS0618
