// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets
{
    /// <summary>
    /// Builds and executes requests for operations under \combos-rfq\v1\rfq\combo-markets
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ComboMarketsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComboMarketsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/combos-rfq/v1/rfq/combo-markets{?cursor*,exclude*,limit*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ComboMarketsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/combos-rfq/v1/rfq/combo-markets{?cursor*,exclude*,limit*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns active markets that can be used as combo legs, ordered by volumedescending. This endpoint is public and does not require CLOBauthentication.Entries in `position_ids`, `outcomes`, and `outcome_prices` correspond byarray index (`[0]` is YES, `[1]` is NO). Use `next_cursor` unchanged inthe next request; a value of `null` indicates the final page.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.ComboMarketsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.CombosRfqErrorResponse">When receiving a 400 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.ComboMarketsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder.ComboMarketsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.ComboMarketsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder.ComboMarketsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.CombosRfqErrorResponse.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.ComboMarketsResponse>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.ComboMarketsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns active markets that can be used as combo legs, ordered by volumedescending. This endpoint is public and does not require CLOBauthentication.Entries in `position_ids`, `outcomes`, and `outcome_prices` correspond byarray index (`[0]` is YES, `[1]` is NO). Use `next_cursor` unchanged inthe next request; a value of `null` indicates the final page.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder.ComboMarketsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder.ComboMarketsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.CombosRfq.V1.Rfq.ComboMarkets.ComboMarketsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns active markets that can be used as combo legs, ordered by volumedescending. This endpoint is public and does not require CLOBauthentication.Entries in `position_ids`, `outcomes`, and `outcome_prices` correspond byarray index (`[0]` is YES, `[1]` is NO). Use `next_cursor` unchanged inthe next request; a value of `null` indicates the final page.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ComboMarketsRequestBuilderGetQueryParameters 
        {
            /// <summary>Opaque cursor returned as `next_cursor` by the previous response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("cursor")]
            public string? Cursor { get; set; }
#nullable restore
#else
            [QueryParameter("cursor")]
            public string Cursor { get; set; }
#endif
            /// <summary>Comma-separated condition IDs to omit, such as markets already shown.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("exclude")]
            public string? Exclude { get; set; }
#nullable restore
#else
            [QueryParameter("exclude")]
            public string Exclude { get; set; }
#endif
            /// <summary>Number of markets to return. Defaults to `50`; maximum `100`.</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
        }
    }
}
#pragma warning restore CS0618
