// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset
{
    /// <summary>
    /// Builds and executes requests for operations under \gamma\events\keyset
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class KeysetRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysetRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gamma/events/keyset{?after_cursor*,ascending*,closed*,created_by*,cyom*,end_date_max*,end_date_min*,event_date*,event_week*,exclude_tag_id*,featured*,featured_order*,game_id*,id*,include_best_lines*,include_chat*,include_children*,include_template*,limit*,liquidity_max*,liquidity_min*,live*,locale*,offset*,order*,parent_event_id*,partner_slug*,recurrence*,related_tags*,series_id*,slug*,start_date_max*,start_date_min*,start_time_max*,start_time_min*,tag_id*,tag_match*,tag_slug*,title_search*,volume_max*,volume_min*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public KeysetRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/gamma/events/keyset{?after_cursor*,ascending*,closed*,created_by*,cyom*,end_date_max*,end_date_min*,event_date*,event_week*,exclude_tag_id*,featured*,featured_order*,game_id*,id*,include_best_lines*,include_chat*,include_children*,include_template*,limit*,liquidity_max*,liquidity_min*,live*,locale*,offset*,order*,parent_event_id*,partner_slug*,recurrence*,related_tags*,series_id*,slug*,start_date_max*,start_date_min*,start_time_max*,start_time_min*,tag_id*,tag_match*,tag_slug*,title_search*,volume_max*,volume_min*}", rawUrl)
        {
        }
        /// <summary>
        /// Returns events using cursor-based (keyset) pagination for stable, efficient paging through large result sets. Use `next_cursor` from each response as `after_cursor` in the next request. The `offset` parameter is explicitly rejected; use `after_cursor` instead.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.KeysetEventsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ValidationError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.InternalError">When receiving a 500 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.ServiceUnavailableError">When receiving a 503 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.KeysetEventsResponse?> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder.KeysetRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.KeysetEventsResponse> GetAsync(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder.KeysetRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "422", global::Soenneker.Polymarket.OpenApiClient.Models.ValidationError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.InternalError.CreateFromDiscriminatorValue },
                { "503", global::Soenneker.Polymarket.OpenApiClient.Models.ServiceUnavailableError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.KeysetEventsResponse>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.KeysetEventsResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns events using cursor-based (keyset) pagination for stable, efficient paging through large result sets. Use `next_cursor` from each response as `after_cursor` in the next request. The `offset` parameter is explicitly rejected; use `after_cursor` instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder.KeysetRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder.KeysetRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Gamma.Events.Keyset.KeysetRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Returns events using cursor-based (keyset) pagination for stable, efficient paging through large result sets. Use `next_cursor` from each response as `after_cursor` in the next request. The `offset` parameter is explicitly rejected; use `after_cursor` instead.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class KeysetRequestBuilderGetQueryParameters 
        {
            /// <summary>Opaque cursor token from a previous response&apos;s next_cursor</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("after_cursor")]
            public string? AfterCursor { get; set; }
#nullable restore
#else
            [QueryParameter("after_cursor")]
            public string AfterCursor { get; set; }
#endif
            /// <summary>Sort direction. Only used when order is set.</summary>
            [QueryParameter("ascending")]
            public bool? Ascending { get; set; }
            [QueryParameter("closed")]
            public bool? Closed { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("created_by")]
            public string[]? CreatedBy { get; set; }
#nullable restore
#else
            [QueryParameter("created_by")]
            public string[] CreatedBy { get; set; }
#endif
            [QueryParameter("cyom")]
            public bool? Cyom { get; set; }
            [QueryParameter("end_date_max")]
            public DateTimeOffset? EndDateMax { get; set; }
            [QueryParameter("end_date_min")]
            public DateTimeOffset? EndDateMin { get; set; }
            [QueryParameter("event_date")]
            public DateTimeOffset? EventDate { get; set; }
            [QueryParameter("event_week")]
            public int? EventWeek { get; set; }
            /// <summary>Tag IDs to exclude. Cannot overlap with tag_id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("exclude_tag_id")]
            public int?[]? ExcludeTagId { get; set; }
#nullable restore
#else
            [QueryParameter("exclude_tag_id")]
            public int?[] ExcludeTagId { get; set; }
#endif
            [QueryParameter("featured")]
            public bool? Featured { get; set; }
            [QueryParameter("featured_order")]
            public bool? FeaturedOrder { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("game_id")]
            public int?[]? GameId { get; set; }
#nullable restore
#else
            [QueryParameter("game_id")]
            public int?[] GameId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("id")]
            public int?[]? Id { get; set; }
#nullable restore
#else
            [QueryParameter("id")]
            public int?[] Id { get; set; }
#endif
            /// <summary>When true, includes BestLines relation</summary>
            [QueryParameter("include_best_lines")]
            public bool? IncludeBestLines { get; set; }
            /// <summary>When true, includes Chats and Series.Chats relations</summary>
            [QueryParameter("include_chat")]
            public bool? IncludeChat { get; set; }
            [QueryParameter("include_children")]
            public bool? IncludeChildren { get; set; }
            /// <summary>When true, includes Templates relation</summary>
            [QueryParameter("include_template")]
            public bool? IncludeTemplate { get; set; }
            /// <summary>Maximum number of results to return (max 500)</summary>
            [QueryParameter("limit")]
            public int? Limit { get; set; }
            [QueryParameter("liquidity_max")]
            public double? LiquidityMax { get; set; }
            [QueryParameter("liquidity_min")]
            public double? LiquidityMin { get; set; }
            [QueryParameter("live")]
            public bool? Live { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("locale")]
            public string? Locale { get; set; }
#nullable restore
#else
            [QueryParameter("locale")]
            public string Locale { get; set; }
#endif
            /// <summary>Not allowed. Returns 422 if provided.</summary>
            [QueryParameter("offset")]
            public int? Offset { get; set; }
            /// <summary>Comma-separated list of JSON field names to order by</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("order")]
            public string? Order { get; set; }
#nullable restore
#else
            [QueryParameter("order")]
            public string Order { get; set; }
#endif
            [QueryParameter("parent_event_id")]
            public int? ParentEventId { get; set; }
            /// <summary>When set, external_partners are attached to matching events</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("partner_slug")]
            public string? PartnerSlug { get; set; }
#nullable restore
#else
            [QueryParameter("partner_slug")]
            public string PartnerSlug { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("recurrence")]
            public string? Recurrence { get; set; }
#nullable restore
#else
            [QueryParameter("recurrence")]
            public string Recurrence { get; set; }
#endif
            [QueryParameter("related_tags")]
            public bool? RelatedTags { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("series_id")]
            public int?[]? SeriesId { get; set; }
#nullable restore
#else
            [QueryParameter("series_id")]
            public int?[] SeriesId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("slug")]
            public string[]? Slug { get; set; }
#nullable restore
#else
            [QueryParameter("slug")]
            public string[] Slug { get; set; }
#endif
            [QueryParameter("start_date_max")]
            public DateTimeOffset? StartDateMax { get; set; }
            [QueryParameter("start_date_min")]
            public DateTimeOffset? StartDateMin { get; set; }
            [QueryParameter("start_time_max")]
            public DateTimeOffset? StartTimeMax { get; set; }
            [QueryParameter("start_time_min")]
            public DateTimeOffset? StartTimeMin { get; set; }
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag_id")]
            public int?[]? TagId { get; set; }
#nullable restore
#else
            [QueryParameter("tag_id")]
            public int?[] TagId { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag_match")]
            public string? TagMatch { get; set; }
#nullable restore
#else
            [QueryParameter("tag_match")]
            public string TagMatch { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("tag_slug")]
            public string? TagSlug { get; set; }
#nullable restore
#else
            [QueryParameter("tag_slug")]
            public string TagSlug { get; set; }
#endif
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
            [QueryParameter("title_search")]
            public string? TitleSearch { get; set; }
#nullable restore
#else
            [QueryParameter("title_search")]
            public string TitleSearch { get; set; }
#endif
            [QueryParameter("volume_max")]
            public double? VolumeMax { get; set; }
            [QueryParameter("volume_min")]
            public double? VolumeMin { get; set; }
        }
    }
}
#pragma warning restore CS0618
