// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Polymarket.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel
{
    /// <summary>
    /// Builds and executes requests for operations under \perps\v1\trade\auto-cancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AutoCancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoCancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/trade/auto-cancel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AutoCancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/perps/v1/trade/auto-cancel", rawUrl)
        {
        }
        /// <summary>
        /// Set a dead man&apos;s switch that cancels all your open orders at the chosentime. The time must be at least 5 seconds in the future. Send 0 to clearan active schedule without triggering it; posting a new time replaces thecurrent one.The switch fires once, then clears itself. It does not cover orders youplace after it fires, so re-arm it if you still need protection.An account can trigger auto-cancel up to 1000 times per UTC day. Afterthat, the API rejects new schedules with the error`auto_cancel_daily_limit_reached` until the next UTC day. Clearing aschedule is always allowed. To check the active deadline and today&apos;strigger count, call [Get Auto-Cancel Status](/api-reference/get-auto-cancel-status).Requires proxy signature, see [proxy signing](/http/signing#2-proxy-signing).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelResponse"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error400">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error404">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.GenericRejected">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error429">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Polymarket.OpenApiClient.Models.Error500">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelResponse?> PatchAsync(global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelResponse> PatchAsync(global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Polymarket.OpenApiClient.Models.Error400.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Polymarket.OpenApiClient.Models.Error404.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Polymarket.OpenApiClient.Models.GenericRejected.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Polymarket.OpenApiClient.Models.Error429.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Polymarket.OpenApiClient.Models.Error500.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelResponse>(requestInfo, global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Set a dead man&apos;s switch that cancels all your open orders at the chosentime. The time must be at least 5 seconds in the future. Send 0 to clearan active schedule without triggering it; posting a new time replaces thecurrent one.The switch fires once, then clears itself. It does not cover orders youplace after it fires, so re-arm it if you still need protection.An account can trigger auto-cancel up to 1000 times per UTC day. Afterthat, the API rejects new schedules with the error`auto_cancel_daily_limit_reached` until the next UTC day. Clearing aschedule is always allowed. To check the active deadline and today&apos;strigger count, call [Get Auto-Cancel Status](/api-reference/get-auto-cancel-status).Requires proxy signature, see [proxy signing](/http/signing#2-proxy-signing).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Polymarket.OpenApiClient.Models.AutoCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Polymarket.OpenApiClient.Perps.V1.Trade.AutoCancel.AutoCancelRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
